// packages/client/pending-deployment/src/components/variables/Variables.tsx
import { DisplayVariable } from '@pivot/client/pending-deployment';
import { button, form, icon, spaced, util } from '@pivot/design/css';
import { Tag } from '@pivot/design/react/tag';
import { cx } from '@pivot/util/classname';

import styles from './variables.module.css';

interface Props {
  clearOverride: (variable_id: string) => void;
  overrideVariable: (variable_id: string, value: string) => void;
  variables: DisplayVariable[];
}

export function Variables({ clearOverride, overrideVariable, variables }: Props) {
  return (
    <>
      {variables.map(({ environment, name, overridden, value, variable_id }) => (
        <div className={cx(form.element)} key={name}>
          <div className={cx('field is-grouped', util['align-vertically'])}>
            <div
              className={cx(
                'control is-expanded',
                form['label-inline'],
                spaced.container,
                util.stretch,
              )}>
              {name}
              <Tag color={environment.color}>{environment.name}</Tag>
            </div>
            <div className={cx('control is-expanded', util.stretch, styles.input)}>
              {overridden ? <span className={styles.overridden}>Overridden</span> : null}
              <input
                className={cx('input', {
                  [styles.overridden]: overridden,
                })}
                onChange={(e) => overrideVariable(variable_id, e.target.value)}
                type="text"
                value={value}
              />
            </div>
            <button
              className={cx(button.base, button.icon)}
              onClick={() => clearOverride(variable_id)}>
              <span className={icon.base}>
                <i className={icon.undo}></i>
              </span>
            </button>
          </div>
        </div>
      ))}
    </>
  );
}

// packages/client/pending-deployment/src/lit/variables.ts
import { html } from 'lit';

import { cx } from '@pivot/util/classname';

import { Model } from '../types';

import styles from './variables.module.css';

export function variables(featuresData: Model['variables']) {
  return html`${featuresData.map(
    ({ name, value }) =>
      html`
        <div class=${styles['variable']}>
          <div class=${cx(styles['inner'], 'field is-grouped')}>
            <div class="control has-icons-left is-expanded">
              <input class="input" type="text" value=${name} />
              <span class="icon is-left">
                <i class="las la-tags"></i>
              </span>
            </div>
            <div class="control has-icons-left is-expanded">
              <input class="input" type="text" value=${value} />
              <span class="icon is-left">
                <i class="las la-key"></i>
              </span>
            </div>
          </div>
        </div>
      `,
  )}`;
}
