// packages/client/pending-deployment/src/components/Variables.tsx
import { DeploymentVariableWithName } from '@pivot/client/deployments';
import { cx } from '@pivot/util/classname';

import styles from './variables.module.css';

interface Props {
  variables: DeploymentVariableWithName[];
  updateVariable: (uuid: string, value: string) => void;
}

export function Variables({ variables, updateVariable }: Props) {
  const onTextChange =
    (uuid: string) => (e: React.ChangeEvent<HTMLInputElement>) => {
      const { value } = e.target;

      updateVariable(uuid, value);
    };

  return (
    <>
      {variables.map(({ name, value, uuid }) => (
        <div className={styles.variable}>
          <div className={cx(styles.inner, 'field is-grouped')}>
            <div className="control has-icons-left is-expanded">
              <input className="input" type="text" value={name} />
              <span className="icon is-left">
                <i className="las la-tags"></i>
              </span>
            </div>
            <div className="control has-icons-left is-expanded">
              <input
                className="input"
                onChange={onTextChange(uuid)}
                type="text"
                value={value}
              />
              <span className="icon is-left">
                <i className="las la-key"></i>
              </span>
            </div>
          </div>
        </div>
      ))}
    </>
  );
}

// packages/client/pending-deployment/src/lit/variables.ts
import { html } from 'lit';

import { cx } from '@pivot/util/classname';

import { Model } from '../types';

import styles from './variables.module.css';

export function variables(featuresData: Model['variables']) {
  return html`${featuresData.map(
    ({ name, value }) =>
      html`
        <div class=${styles['variable']}>
          <div class=${cx(styles['inner'], 'field is-grouped')}>
            <div class="control has-icons-left is-expanded">
              <input class="input" type="text" value=${name} />
              <span class="icon is-left">
                <i class="las la-tags"></i>
              </span>
            </div>
            <div class="control has-icons-left is-expanded">
              <input class="input" type="text" value=${value} />
              <span class="icon is-left">
                <i class="las la-key"></i>
              </span>
            </div>
          </div>
        </div>
      `,
  )}`;
}
